@startuml
title 列統計登録・更新
hide footbox

box #LightBlue
control "metadata-managerのAPIを利用する\nTsurugiのコンポーネント" as ogawayama
end box
box "メタデータ管理基盤" #LightGreen
control "metadata-manager" as metadata_manager
entity "メタデータ格納先" as datastore
end box

activate ogawayama
ogawayama -> ogawayama : 列統計 計算
ogawayama -> metadata_manager : 列統計 登録・更新
activate metadata_manager
metadata_manager -> datastore :  列統計 登録・更新
activate datastore
metadata_manager <-- datastore : ErrorCode
deactivate datastore
ogawayama <-- metadata_manager : ErrorCode
deactivate metadata_manager
@enduml

@startuml
title 表統計登録・更新
hide footbox

box #LightBlue
control "metadata-managerのAPIを利用する\nTsurugiのコンポーネント" as ogawayama
end box
box "メタデータ管理基盤" #LightGreen
control "metadata-manager" as metadata_manager
entity "メタデータ格納先" as datastore
end box

activate ogawayama
ogawayama -> ogawayama : 表統計 計算
ogawayama -> metadata_manager : 表統計 登録・更新
activate metadata_manager
metadata_manager -> datastore :  表統計 登録・更新
activate datastore
metadata_manager <-- datastore : ErrorCode
deactivate datastore
ogawayama <-- metadata_manager : ErrorCode
deactivate metadata_manager
@enduml

@startuml
title 列統計参照
hide footbox

box #LightBlue
control "metadata-managerのAPIを利用する\nTsurugiのコンポーネント" as ogawayama
end box
box "メタデータ管理基盤" #LightGreen
control "metadata-manager" as metadata_manager
entity "メタデータ格納先" as datastore
end box

activate ogawayama
ogawayama -> metadata_manager : 列統計 参照
activate metadata_manager
metadata_manager -> datastore :  列統計 参照
activate datastore
metadata_manager <-- datastore : 列統計
deactivate datastore
ogawayama <-- metadata_manager : 列統計、ErrorCode
deactivate metadata_manager
@enduml

@startuml
title 表統計参照
hide footbox

box #LightBlue
control "metadata-managerのAPIを利用する\nTsurugiのコンポーネント" as ogawayama
end box
box "メタデータ管理基盤" #LightGreen
control "metadata-manager" as metadata_manager
entity "メタデータ格納先" as datastore
end box

activate ogawayama
ogawayama -> metadata_manager : 表統計 参照
activate metadata_manager
metadata_manager -> datastore :  表統計 参照
activate datastore
metadata_manager <-- datastore : 表統計を含むTableメタデータ
deactivate datastore
ogawayama <-- metadata_manager : 表統計を含むTableメタデータ、\nErrorCode
deactivate metadata_manager
@enduml

@startuml
title 列統計削除
hide footbox

box #LightBlue
control "metadata-managerのAPIを利用する\nTsurugiのコンポーネント" as ogawayama
end box
box "メタデータ管理基盤" #LightGreen
control "metadata-manager" as metadata_manager
entity "メタデータ格納先" as datastore
end box

activate ogawayama
ogawayama -> metadata_manager : 列統計 削除
activate metadata_manager
metadata_manager -> datastore :  列統計 削除
activate datastore
metadata_manager <-- datastore : ErrorCode
deactivate datastore
ogawayama <-- metadata_manager : ErrorCode
deactivate metadata_manager
@enduml
