'/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
@startuml SequenceDiagram_authentication
skinparam responseMessageBelowArrow true

title ユーザ認証処理

box #White
  boundary "OLTP I/F" as ogawayama
end box

box "認証管理基盤\n（authentication-manager）" #LightYellow
  control Authentication
  control AuthenticationProvider
  control DBSessionManager
end box

box データベース #LightBlue
  database PostgreSQL
end box

activate ogawayama
  ogawayama -> Authentication ++ : ユーザ認証APIを実行\n auth_user()
    Authentication -> AuthenticationProvider ++ : ユーザ認証関数を実行\n auth_user()
      AuthenticationProvider -> DBSessionManager ++ : DB接続検査関数を実行\n attempt_connection()
alt サーバアクセス失敗
        DBSessionManager ->x PostgreSQL : DBサーバ状態検査\n PQping()
        DBSessionManager --> DBSessionManager : PQPING_OK以外
      AuthenticationProvider <-- DBSessionManager : ErrorCode::CONNECTION_FAILURE
    Authentication <-- AuthenticationProvider : ErrorCode::CONNECTION_FAILURE
  ogawayama <-- Authentication : ErrorCode::CONNECTION_FAILURE
else サーバアクセス成功
        DBSessionManager ->o PostgreSQL : DBサーバ状態検査\n PQping()
        DBSessionManager --> DBSessionManager : PQPING_OK
        |||
        DBSessionManager -> PostgreSQL ++: DB接続要求\n PQconnectdb()
          PostgreSQL -> PostgreSQL ++ #LightGray  : 認証処理
          return
        return 処理結果
        DBSessionManager -> DBSessionManager ++ #LightGray : 処理結果取得\n PQstatus()
alt 接続成功 (CONNECTION_OK)
        DBSessionManager --> DBSessionManager : 接続成功 (CONNECTION_OK)
      AuthenticationProvider <-- DBSessionManager : ErrorCode::OK
    Authentication <-- AuthenticationProvider : ErrorCode::OK
  ogawayama <-- Authentication : ErrorCode::OK
else 接続失敗 (CONNECTION_OK以外)
        DBSessionManager --> DBSessionManager -- : 接続失敗 (CONNECTION_OK以外)
      AuthenticationProvider <-- DBSessionManager -- : ErrorCode::AUTHENTICATION_FAILURE
    Authentication <-- AuthenticationProvider -- : ErrorCode::AUTHENTICATION_FAILURE
  ogawayama <-- Authentication -- : ErrorCode::AUTHENTICATION_FAILURE
end
end

@enduml
