@startuml
title 列統計・表統計管理機能
hide footbox

box #LightBlue
control "metadata-managerのAPIを利用する\nコンポーネント" as ogawayama
end box
box "メタデータ管理基盤" #LightGreen
control "metadata-manager" as metadata_manager
entity "メタデータ格納先" as datastore
end box

activate ogawayama
ogawayama -> ogawayama : 列統計・表統計 計算
ogawayama -> metadata_manager : 列統計・表統計 格納
activate metadata_manager
metadata_manager -> datastore :  列統計・表統計 格納
activate datastore
metadata_manager <-- datastore : 成功
deactivate datastore
ogawayama <-- metadata_manager : 成功
deactivate metadata_manager
@enduml
