' ===============================================
' ユーザ認証
' ===============================================
@startuml auth_user
title ユーザ認証機能

actor User as user
boundary "OLTP I/F" as ogawayama
control OLTP as oltp
control AuthManager as auth_man
database PostgreSQL as pg

== ユーザ登録 ==
user -> pg : ユーザ（ロール）作成要求
activate pg
  pg -> pg : ロール作成
  activate pg
  deactivate pg
  pg --> user 
deactivate pg

== バッチジョブ実行 ==
user -> ogawayama : ユーザ認証要求 & ジョブ実行要求
activate ogawayama
  ogawayama -> auth_man : ユーザ認証要求
  activate auth_man
    auth_man -> pg : ログイン要求
    activate pg
      pg -> pg : ログイン処理
      activate pg
      deactivate pg
      pg --> auth_man : 処理結果
    deactivate pg
    auth_man --> ogawayama : ユーザ認証結果
  deactivate auth_man

alt 認証成功
  ogawayama -> oltp : ジョブ実行依頼
  activate oltp
    oltp -> oltp : ジョブ実行
    activate oltp
    deactivate oltp
    oltp --> ogawayama : 実行結果
  deactivate oltp
  ogawayama --> user : ジョブ実行結果
  deactivate ogawayama
else 認証失敗
  ogawayama --> user : ユーザ認証失敗
end
@enduml

' ===============================================
' ユーザ認証
' ===============================================
@startuml auth_user2
autoactivate on
title ユーザ認証機能

actor User as user
boundary "OLTP I/F" as ogawayama
control OLTP as oltp
control AuthManager as auth_man
database PostgreSQL as pg

== ユーザ登録 ==
user -> pg : ユーザ（ロール）作成要求
  pg -> pg : ロール作成
  return
return

== バッチジョブ実行 ==
user -> ogawayama : ユーザ認証要求 & ジョブ実行要求
  ogawayama -> auth_man : ユーザ認証要求
    auth_man -> pg : ログイン要求
      pg -> pg : ログイン処理
      return
    return 処理結果
  return ユーザ認証結果

alt 認証成功
  ogawayama -> oltp : ジョブ実行依頼
    oltp -> oltp : ジョブ実行
    return
  return 実行結果
return ジョブ実行結果
else 認証失敗
ogawayama --> user : ユーザ認証失敗
end
@enduml
