' ===============================================
' 
' ===============================================
@startuml frontend
package frontend {
class alt_utility

class create_role
class drop_role
class alter_role
class grant_role
class revoke_role

class create_table
class grant_table
class revoke_table

class create_view
class drop_view


class rolecmd
class tablecmd
class viewcmd

}
alt_utility --> create_table
alt_utility --> grant_table
alt_utility --> revoke_table
alt_utility --> create_role
alt_utility --> drop_role
alt_utility --> alter_role
alt_utility --> grant_role
alt_utility --> revoke_role
alt_utility --> create_view
alt_utility --> drop_view

create_table *--> tablecmd
grant_table *--> tablecmd
revoke_table *--> tablecmd

create_role *--> rolecmd
drop_role *--> rolecmd
alter_role *--> rolecmd
grant_role *--> rolecmd
revoke_role *--> rolecmd

create_view *--> viewcmd
drop_view *--> viewcmd

package manager {
package message{
  class MessageBroker{
    Status send_message(Message *message)
  }
}
package metadata-manager{}

}

@enduml

' ===============================================
' Frontend All Role Class
' ===============================================
@startuml Frontend_Role_all_class
package frontend {
class alt_utility

class create_role
class drop_role
class alter_role
class grant_role
class revoke_role


class rolecmd

alt_utility --> create_role
alt_utility --> drop_role
alt_utility --> alter_role
alt_utility --> grant_role
alt_utility --> revoke_role


create_role *--> rolecmd
drop_role *--> rolecmd
alter_role *--> rolecmd
grant_role *--> rolecmd
revoke_role *--> rolecmd
}


package manager {
package metadata{
  abstract Metadata{
    ErrorCode init() 
    ErrorCode add(boost::property_tree::ptree& object)
    ErrorCode add(boost::property_tree::ptree& object,ObjectIdType* object_id)
    ErrorCode remove(const char* object_name, ObjectIdType* object_id) 
    ErrorCode remove(const ObjectIdType object_id)
    ErrorCode get(std::string_view object_name,boost::property_tree::ptree& object)
    ErrorCode get(const ObjectIdType object_id,boost::property_tree::ptree& object)    
  }
  class Roles{
    ErrorCode init() 
    ErrorCode update(std::string_view object_name,boost::property_tree::ptree& object)
    ErrorCode update(ObjectIdType object_id, boost::property_tree::ptree& object)
    ErrorCode remove(const char* object_name, ObjectIdType* object_id) 
    ErrorCode remove(const ObjectIdType object_id)
    ErrorCode get(std::string_view object_name,boost::property_tree::ptree& object)
    ErrorCode get(const ObjectIdType object_id,boost::property_tree::ptree& object)
  }
  Roles --|> Metadata
}
package message{
  class MessageBroker{
    Status send_message(Message *message)
  }
  class Status{}
  class Receiver{}
  class Message{}
  class CreateRoleMessage{}
  class DropRoleMessage{}
  class AlterRoleMessage{}
  class GrantRoleMessage{}
  class RevokeRoleMessage{}
  CreateRoleMessage --|> Message
  DropRoleMessage --|> Message
  AlterRoleMessage --|> Message
  GrantRoleMessage --|> Message
  RevokeRoleMessage --|> Message
  Message --o Receiver
  MessageBroker --> Message
  MessageBroker --> Status
  Receiver --> Status
}


}
create_role --o CreateRoleMessage
drop_role   --o DropRoleMessage
alter_role  --o AlterRoleMessage
grant_role  --o GrantRoleMessage
revoke_role --o RevokeRoleMessage
rolecmd --o Roles
@enduml
