' =========================================================
' 全体シーケンス概要
' =========================================================
@startuml entire_seq
hide footbox

control PostgreSQL as pg
control "frontend(alt-utility)" as frontend
control "manager(message-broker)" as msgbroker
control "metadata-manager" as metadata

control "ogawayama" as stub

activate pg
  pg -> frontend : hook DDL command
  activate frontend
    frontend -> pg : DDL command
    activate pg
      alt option
    return
    frontend -> msgbroker : message(DDL command)
    activate msgbroker
      msgbroker -> stub : send_message(DDL command)
      activate stub
        alt option
        stub -> stub
        activate stub
          stub -> metadata : get/update/remove
          activate metadata
            alt option
            metadata -> pg : DDL command
            activate pg
              alt option
            return : DDL command result
          return
        return
      return 
    return
  return
deactivate pg
@enduml
